# - Device Configuration -
# The Path to look for the file(s) that represent the Device Information Models to load into the Agent.
# The path can either be a single file or a directory.
# The path can be absolute or relative to the executable's directory
devices: devices

# - SHDR Adapter Configuration -
# The Agent is able to receive data through a TCP port using the SHDR protocol
adapters:
- hostname: localhost
  port: 7878
  reconnectInterval: 1000

# Sets whether a Device Model can be sent from an SHDR Adapter
allowShdrDevice: false


# - Windows Service Configuration

# Changes the service name when installing or removing the service. This allows multiple agents to run as services on the same machine.
serviceName: MTConnect-Agent-MQTT-Relay

# Sets the Service Start Type. True = Auto | False = Manual
serviceAutoStart: true


# - MQTT Configuration -

# The hostname of the MQTT broker to publish messages to
server: localhost

# The port number of the MQTT broker to publish messages to
port: 1883

# The Intervals to publish Observations at (in milliseconds)
observationIntervals:
- 0
- 100
- 1000


# - Agent Configuration -

# Sets the default MTConnect version to output response documents for.
defaultVersion: 2.1

# Overwrite timestamps with the agent time. This will correct clock drift but will not give as accurate relative time since it will not take into consideration network latencies. This can be overridden on a per adapter basis.
ignoreTimestamps: false

# Sets the default for Converting Units when adding Observations
convertUnits: true

# Sets the default for Ignoring the case of Observation values. Applicable values will be converted to uppercase
ignoreObservationCase: true

# Sets the default input validation level when new Observations are added to the Agent. 0 = Ignore, 1 = Warning, 2 = Strict
inputValidationLevel: Ignore

# Sets whether Configuration files are monitored. If enabled and a configuration file is changed, the Agent will restart
monitorConfigurationFiles: true

# Sets the minimum time (in seconds) between Agent restarts when MonitorConfigurationFiles is enabled
configurationFileRestartInterval: 2

# Sets whether Agent Metrics are captured (ex. ObserationUpdateRate, AssetUpdateRate)
enableMetrics: true
