# - HTTP Client Adapter Configuration -
# The Agent is able to receive data by reading from other MTConnect HTTP Agents
clients:
- address: localhost
  port: 5000
  deviceKey: OKUMA-Lathe


# - Windows Service Configuration

# Changes the service name when installing or removing the service. This allows multiple agents to run as services on the same machine.
serviceName: MTConnect-Agent-MQTT-Gateway

# Sets the Service Start Type. True = Auto | False = Manual
serviceAutoStart: true


# - MQTT Configuration -

# The hostname of the MQTT broker to publish messages to
server: localhost

# The port number of the MQTT broker to publish messages to
port: 1883


# - Buffer Configuration -
# The Agent has an internal buffer that retains the information that the Agent can respond with according to the MTConnect Standard.
# There is also a Durable File backed buffer that can retain the information in the Agent between Agent restarts

# The maximum number of Observations the agent can hold in its buffer
observationBufferSize: 150000

# The maximum number of assets the agent can hold in its buffer
assetBufferSize: 1000

# Sets whether the Agent buffers are durable and retain state after restart
durable: false

# Sets whether the durable Agent buffers use Compression
useBufferCompression: false


# - Agent Configuration -

# Sets the default MTConnect version to output response documents for.
defaultVersion: 2.1

# Overwrite timestamps with the agent time. This will correct clock drift but will not give as accurate relative time since it will not take into consideration network latencies. This can be overridden on a per adapter basis.
ignoreTimestamps: false

# Sets the default for Converting Units when adding Observations
convertUnits: true

# Sets the default for Ignoring the case of Observation values. Applicable values will be converted to uppercase
ignoreObservationCase: true

# Sets the default input validation level when new Observations are added to the Agent. 0 = Ignore, 1 = Warning, 2 = Strict
inputValidationLevel: Ignore

# Sets whether Configuration files are monitored. If enabled and a configuration file is changed, the Agent will restart
monitorConfigurationFiles: true

# Sets the minimum time (in seconds) between Agent restarts when MonitorConfigurationFiles is enabled
configurationFileRestartInterval: 2

# Sets whether Agent Metrics are captured (ex. ObserationUpdateRate, AssetUpdateRate)
enableMetrics: true
