name: MTConnect.NET
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '7.0.x'
jobs:
  MTConnect-NET-Common:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-Common
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-Common
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-Common
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-Common
  MTConnect-NET-HTTP:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-HTTP
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-HTTP
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-HTTP
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-HTTP
  MTConnect-NET-HTTP-AspNetCore:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-HTTP-AspNetCore
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-HTTP-AspNetCore
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-HTTP-AspNetCore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-HTTP-AspNetCore
  MTConnect-NET-XML:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-XML
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-XML
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-XML
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-XML
  MTConnect-NET-SHDR:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-SHDR
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-SHDR
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-SHDR
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-SHDR
  MTConnect-NET-MQTT:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-MQTT
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-MQTT
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-MQTT
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-MQTT

