name: MTConnect.NET
on:
  push:
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'README.md'
env:
  DOTNET_VERSION: '6.0.x'
jobs:
  MTConnect-NET-Common:
    name: build-and-test-${{matrix.os}}-MTConnect-NET-Common
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Clean
      run: dotnet clean --configuration Release
      working-directory: src/MTConnect.NET-Common
    - name: Build
      run: dotnet build --configuration Release --force
      working-directory: src/MTConnect.NET-Common
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: src/MTConnect.NET-Common

